version: '2.1'

services:
  opal-fines-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_FINES_DB_HOST=opal-fines-db
    ports:
      - $SERVER_PORT:$SERVER_PORT

  opal-fines-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=opal-fines-db
      - POSTGRES_USER=opal-fines
      - POSTGRES_PASSWORD=opal-fines
    ports:
      - 5432:5432
    volumes:
      - opal-database-data:/var/lib/postgresql/data

volumes:
  opal-database-data:
