java:
  applicationPort: 4550
  image: 'sdshmctspublic.azurecr.io/opal/account-enquiry:latest'
  ingressHost: opal-account-enquiry-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: false
